### ISSUE TITLE
Razor Language Service does not highlight TagHelpers for pre-opened Razor files.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1154]
If you close a solution while having a Razor file (that has TagHelpers) open; re-open it, the TagHelper highlighting will not re-light up.

Reproduction steps provided by a customer:

I can consistently reproduce the issue on a new project
-	Open VS, create a new ASP.NET Core app with the MVC template.
-	Open _Layout.cshtml: now I see the purple tags of environment, link, and attributes asp-controller, etc... and I get Intellisense if I type new taghelpers
-	Close solution, open it again. Now I get the last file I had open _Layout.cshtml: all is gone
-	If I close and reopen the file I get taghelper Intellisense
-	Same happens if I closed the file before closing the solution. First time I open doesn’t work. Close and reopen, it shows

@ToddGrun @alexgav This is probably on the editor side of things but might also exist on our side. I filed the issue here for now until we can determine which is at fault.

**Comment by rynowak** [comment]
Is this an issue with the released version of RLS?

**Comment by NTaylorMullen** [comment]
> Is this an issue with the released version of RLS?

Yes

**Comment by rynowak** [comment]
OK. I think the fix for this will have to wait for the update 3 previews sadly. This is definitely in the edtior code

**Comment by rynowak** [comment]
@NTaylorMullen - does this repro on update 3?

**Comment by NTaylorMullen** [comment]
I don't have a box that has this yet. @alexgav could you try this out real quick?

**Comment by rynowak** [comment]
Let's just verify this next week then

**Comment by ScottKaye** [comment]
Also running into this issue with a new install of VS2017.  However I can't even get highlighting to appear ever, even after following the steps in the OP.

With just the default extensions + GitHub (Razor Language Services disabled), I consistently get an error when reopening a .cshtml file in a new project for the first time.  The relevant bit out of ActivityLog.xml is:

```xml
<entry>
    <record>611</record>
    <time>2017/04/08 23:30:36.852</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>
    	System.ArgumentException: An item with the same key has already been added.
    	   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
    	   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
    	   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker.AddProject(AbstractProject project)
    	   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject..ctor(VisualStudioProjectTracker projectTracker, Func`2 reportExternalErrorCreatorOpt, String projectDisplayName, String projectFilePath, IVsHierarchy hierarchy, String language, Guid projectGuid, String binOutputPath, IServiceProvider serviceProvider, VisualStudioWorkspaceImpl visualStudioWorkspaceOpt, HostDiagnosticUpdateSource hostDiagnosticUpdateSourceOpt, ICommandLineParserService commandLineParserServiceOpt)
    	   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProjectFactory.Microsoft.VisualStudio.LanguageServices.ProjectSystem.IWorkspaceProjectContextFactory.CreateProjectContext(String languageName, String projectDisplayName, String projectFilePath, Guid projectGuid, Object hierarchy, String binOutputPath)
    	   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.UnconfiguredProjectContextProvider.<>c__DisplayClass24_0.<<CreateProjectContextAsyncCore>b__0>d.MoveNext()

    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()

    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()

    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.UnconfiguredProjectContextProvider.<CreateProjectContextAsyncCore>d__24.MoveNext()

    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.UnconfiguredProjectContextProvider.<CreateProjectContextAsync>d__12.MoveNext()
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
    	   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.<>c__DisplayClass29_0.<<UpdateProjectContextAsync>b__0>d.MoveNext()
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.<>c__DisplayClass27_0`1.<<ExecuteWithinLockAsync>b__0>d.MoveNext()
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.<UpdateProjectContextAsync>d__29.MoveNext()
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.<UpdateProjectContextAndSubscriptionsAsync>d__26.MoveNext()
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.<InitializeCoreAsync>d__22.MoveNext()
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedAsync.<<-ctor>b__4_0>d.MoveNext()
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass13_1.<<GetValueAsync>b__0>d.MoveNext()
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.VsContainedLanguageComponentsFactoryBase.<InitializeCoreAsync>d__16.MoveNext()
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedAsync.<<-ctor>b__4_0>d.MoveNext()
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass13_1.<<GetValueAsync>b__0>d.MoveNext()
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.VsContainedLanguageComponentsFactoryBase.<>c__DisplayClass18_0.<<GetContainedLanguageFactoryForFile>b__0>d.MoveNext()
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedAsync.<<InitializeAsync>b__27_0>d.MoveNext()
    	  
    	--- End of stack trace from previous location where exception was thrown ---
    	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    	   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
    	   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.VsContainedLanguageComponentsFactoryBase.GetContainedLanguageFactoryForFile(String filePath, IVsHierarchy&amp; hierarchy, UInt32&amp; itemid, IVsContainedLanguageFactory&amp; containedLanguageFactory)
    	   at Microsoft.VisualStudio.Html.Package.ContainedLanguage.Server.ProjectKServerContainedLanguageSupport.InitContainedLanguage()
    	   at Microsoft.VisualStudio.Html.Package.ContainedLanguage.Server.ProjectKServerContainedLanguageSupport..ctor(ITextBuffer textBuffer, ITextView textView)
    	   at Microsoft.VisualStudio.Html.Package.ContainedLanguage.Server.ServerContainedLanguageSupport.EnsureConnected(ITextView textView, ITextBuffer textBuffer)
    	   at Microsoft.VisualStudio.Html.Package.ContainedLanguage.Server.ServerContainedLanguageSupportViewTracker.OnTextViewCreated(ITextView textView, ITextBuffer textBuffer)
    	   at Microsoft.Web.Editor.Controller.TextViewConnectionListener.<>c__DisplayClass26_0.<OnTextViewGotAggregateFocus>b__0()
    	   at Microsoft.Web.Editor.Utility.GuardedOperations.InvokeExtensionPoint(Object errorSource, Action action)</description>
  </entry>
```

About:

```
Microsoft Visual Studio Community 2017
Version 15.0.26228.12 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Community

---
ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.
---
```

**Comment by rynowak** [comment]
@ScottKaye - this issue isn't in RLS, it's a lower level of VS https://github.com/dotnet/project-system/issues/1925

**Comment by ScottKaye** [comment]
Ah, sorry about that.  Figured it might have been related.

**Comment by rynowak** [comment]
No worries

**Comment by rynowak** [comment]
@NTaylorMullen - still an issue?

**Comment by NTaylorMullen** [comment]
@rynowak Still an issue. Will need to investigate further to find out why.

**Comment by NTaylorMullen** [comment]
Findings:
- Tooling is invoking `TagHelperDescriptor` resolution prior to the Roslyn workspace being instantiated. This means we attempt to locate TagHelpers on a workspace that hasn't been populated. If you force the operation to spin a few cycles and wait for the workspace resolution all works fine.
- Tooling will need to wait for Roslyn's workspaces to be fully initialized.
- Tooling doesn't seem to be re-invoking descriptor resolution when a cshtml file is open if a restore is not needed.
- After a build descriptors light up fine.

Removed investigate label.

**Comment by rynowak** [comment]
OK, so it looks like for now this is external to us. I'm going to start making use of the external tag.

**Comment by NTaylorMullen** [comment]
Move out?

**Comment by rynowak** [comment]
Yes, let's move out of 15.3 and follow up with WTE about risk/when they would be able to ship a fix for this

**Comment by rynowak** [comment]
I'm parking this in preview3 because I want us to at least figure out when this can fixed.

**Comment by mschulz531** [comment]
Still happening...any update on a fix?

Microsoft Visual Studio Enterprise 2017 
Version 15.3.0
VisualStudio.15.Release/15.3.0+26730.3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

=====================
9/4/2017 9:05:39 AM
Recoverable
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.InprogressState.SupportedDiagnosticId(ProjectId projectId, String id)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.SupportedDiagnosticId(ProjectId projectId, String id)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ProjectExternalErrorReporter.CanHandle(String errorId)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ProjectExternalErrorReporter.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.Microsoft.VisualStudio.Shell.Interop.IVsLanguageServiceBuildErrorReporter2.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Build.LanguageServiceErrorListProvider.<AddMessageCoreAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService.<AddMessagesAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService.<ProcessQueueAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.InprogressState.SupportedDiagnosticId(ProjectId projectId, String id)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.SupportedDiagnosticId(ProjectId projectId, String id)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ProjectExternalErrorReporter.CanHandle(String errorId)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ProjectExternalErrorReporter.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.Microsoft.VisualStudio.Shell.Interop.IVsLanguageServiceBuildErrorReporter2.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Build.LanguageServiceErrorListProvider.<AddMessageCoreAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService.<AddMessagesAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService.<ProcessQueueAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================
9/4/2017 9:05:39 AM
Recoverable
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.InprogressState.SupportedDiagnosticId(ProjectId projectId, String id)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.SupportedDiagnosticId(ProjectId projectId, String id)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ProjectExternalErrorReporter.CanHandle(String errorId)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ProjectExternalErrorReporter.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.Microsoft.VisualStudio.Shell.Interop.IVsLanguageServiceBuildErrorReporter2.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Build.LanguageServiceErrorListProvider.<AddMessageCoreAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService.<AddMessagesAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService.<ProcessQueueAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.InprogressState.SupportedDiagnosticId(ProjectId projectId, String id)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.SupportedDiagnosticId(ProjectId projectId, String id)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ProjectExternalErrorReporter.CanHandle(String errorId)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ProjectExternalErrorReporter.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.Microsoft.VisualStudio.Shell.Interop.IVsLanguageServiceBuildErrorReporter2.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Build.LanguageServiceErrorListProvider.<AddMessageCoreAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService.<AddMessagesAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService.<ProcessQueueAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================
9/4/2017 9:05:42 AM
Recoverable
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.InprogressState.SupportedDiagnosticId(ProjectId projectId, String id)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.SupportedDiagnosticId(ProjectId projectId, String id)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ProjectExternalErrorReporter.CanHandle(String errorId)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ProjectExternalErrorReporter.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.Microsoft.VisualStudio.Shell.Interop.IVsLanguageServiceBuildErrorReporter2.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Build.LanguageServiceErrorListProvider.<AddMessageCoreAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService.<AddMessagesAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService.<ProcessQueueAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.InprogressState.SupportedDiagnosticId(ProjectId projectId, String id)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.SupportedDiagnosticId(ProjectId projectId, String id)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ProjectExternalErrorReporter.CanHandle(String errorId)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ProjectExternalErrorReporter.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.Microsoft.VisualStudio.Shell.Interop.IVsLanguageServiceBuildErrorReporter2.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Build.LanguageServiceErrorListProvider.<AddMessageCoreAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService.<AddMessagesAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService.<ProcessQueueAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================

**Comment by NTaylorMullen** [comment]
This is being tracked in TFS at: https://devdiv.visualstudio.com/DevDiv/_workitems?id=489897

**Comment by rynowak** [comment]
This was fixed in the non-OSS bits. This will ship in 15.5
