### ISSUE TITLE
@namespace directive crashes VS if at end of file with an invalid namespace name.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1393]
The invalid type name that gets picked up here is `SomeName.` (note the dot at the end)

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.HandleDirective(Microsoft.AspNetCore.Razor.Language.DirectiveDescriptor)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser+<>c__DisplayClass93_0.<SetupDirectives>b__0()
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.AfterTransition()
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.AtTransition(Microsoft.AspNetCore.Razor.Language.Legacy.CSharpSymbol)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.ParseBlock()
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.OtherParserBlock()
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.SkipToAndParseCode(System.Func`2<Microsoft.AspNetCore.Razor.Language.Legacy.HtmlSymbol,Boolean>)
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.SkipToAndParseCode(Microsoft.AspNetCore.Razor.Language.Legacy.HtmlSymbolType)
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.ParseDocument()
   at Microsoft.AspNetCore.Razor.Language.Legacy.RazorParser.Parse(Microsoft.AspNetCore.Razor.Language.RazorSourceDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorSyntaxTree.Parse(Microsoft.AspNetCore.Razor.Language.RazorSourceDocument, Microsoft.AspNetCore.Razor.Language.RazorParserOptions)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorParsingPhase.ExecuteCore(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorTemplateEngine.GenerateCode(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.Legacy.BackgroundParser+BackgroundThread.ParseChange(Microsoft.AspNetCore.Razor.Language.Legacy.ITextBuffer, System.Threading.CancellationToken)
   at Microsoft.AspNetCore.Razor.Language.Legacy.BackgroundParser+BackgroundThread.WorkerLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

![razor-crash](https://cloud.githubusercontent.com/assets/7574/26607419/44c40730-454b-11e7-9487-ecb78b665c6a.gif)

VS: 15.3.0 Preview 1.0 [26526.1.d15rel]

**Comment by NTaylorMullen** [comment]
@rynowak / @DamianEdwards please assign a milestone/project.

**Comment by anurse** [comment]
Thanks @NTaylorMullen . I'd appreciate if you can tag me in the PR when you have it (don't need to be a reviewer)

**Comment by rynowak** [comment]
Ideally this makes it for 15.3 preview3. Let's figure out the approval process for that.

**Comment by NTaylorMullen** [comment]
2e8c154fcb2952b9b42610258dd600883fda461f
1f32a8322e3c8e9e8d6a79f6d3db33623de93e88
