### ISSUE TITLE
Flakey test CreateDescriptor_AddsDiagnostic_ForViewComponentWithNoInvokeMethod

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1407]
This seems to be occasionally null refing on the CI. From a brief look I don't know how that's possible; worth spending more time to investigate.

**Comment by rynowak** [comment]
If we're sharing a compilation across tests it could be a race condition.

Do we have a call stack?

**Comment by NTaylorMullen** [comment]
Call stack:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.CodeAnalysis.TestCompilation.Create(Assembly assembly, SyntaxTree syntaxTree)
   at Microsoft.AspNetCore.Mvc.Razor.Extensions.ViewComponentTagHelperDescriptorFactoryTest.CreateDescriptor_AddsDiagnostic_ForViewComponentWithNoInvokeMethod() in C:\b\w\33bdfc1cae7b2a38\.r\Razor\test\Microsoft.AspNetCore.Mvc.Razor.Extensions.Test\ViewComponentTagHelperDescriptorFactoryTest.cs:line 143
```

Flakeyness: http://aspnetci/project.html?projectId=XPlat&tab=testDetails&testNameId=-4601442549646515137#analysis

**Comment by NTaylorMullen** [comment]
> If we're sharing a compilation across tests it could be a race condition.

We shouldn't be. That's why the `TestCompilation` requires you to create a new one each time.

**Comment by rynowak** [comment]
Fixing this, I found the problem.
