### ISSUE TITLE
Microsoft.NET.Sdk with Razor support

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#1951]
_From @bgever on August 10, 2017 9:55_

I'm trying to get Razor syntax support for Visual Studio 2017 in a `Microsoft.NET.Sdk` library, which is dynamically loaded into a `Microsoft.NET.Sdk.Web` project.

I've noticed that when I change the library to the Web SDK, .cshtml files get proper support for Razor code, so that I can access `@Html` or `@Context` with IntelliSense, and reports no longer errors (red squiggles).

However, with that SDK I have to add an app entry point, and the output is an EXE. Moreover, when loading the library as an Application Part in MVC, similar to https://github.com/dotnet/sdk/issues/1213, then I get the below exception.

```
System.InvalidOperationException: Can not find compilation library location for package 'quantifeed.webapp.cub'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.GetCompilationReferences()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.get_CompilationReferences()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
```

Is there a way to get Razor support in VS 2017 with a `Microsoft.NET.Sdk`  SDK?

_Copied from original issue: dotnet/sdk#1481_

**Comment by rynowak** [comment]
We are planning to convert Razor into an MSBuild SDK in 2.1.0-preview**2**.

However this issue just looks like a missing dependency. Is `quantifeed.webapp.cub` in your app's binary directory

**Comment by bgever** [comment]
No, this is a plug-in library, and therefore not a full .Sdk.Web project. If I change it to a .Web SDK, it will try to compile it as such. The plugin library gets loaded at runtime using ASP.NET Core’s ability to load plugins.

In the library I do have Razor files, and they are not being recognized in VS.

**Comment by rynowak** [comment]
Can you try adding this to your project file?
```
  <ItemGroup>
    <ProjectCapability Include="DotNetCoreWeb" />
    <ProjectCapability Include="AspNetCore" />
    <ProjectCapability Include="Web" />
</ItemGroup>
```

@NTaylorMullen - we should discuss this. We should add a Razor-specific capability to the Razor targets and consume that in our tooling.

**Comment by bgever** [comment]
Thanks for the suggestion @rynowak. I'm not sure what changed, but I no longer get the unrecognized symbols in cshtml files anymore. I'm using VS Enterprise 2017 15.5.4. The csproj file looks like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.6;net461</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*.cshtml">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Tests\**" />
    <Compile Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="4.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.6" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\(dependency).csproj" />
    <!-- [...] -->
  </ItemGroup>

</Project>
```

**Comment by mkArtakMSFT** [comment]
@rynowak, @NTaylorMullen do we want to track the suggested work as part of this issue or should we file a separate one?

**Comment by bgever** [comment]
Thanks for the follow-up. I'm fine to close this issue.

**Comment by rynowak** [comment]
Thanks!
