### ISSUE TITLE
FLakey test Publish_UsesRazorSDK

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1976]
http://aspnetci/project.html?projectId=XPlat&testNameId=8240098287330275919&tab=testDetails

**Comment by ryanbrandenburg** [comment]
```
Assert.True() Failure
Expected: True
Actual:   False
   at FunctionalTests.RazorSdkUsedTest_CoreCLR.<Publish_UsesRazorSDK>d__4.MoveNext() in C:\b\w\33bdfc1cae7b2a38\modules\MvcPrecompilation\test\FunctionalTests\CoreCLRTests\RazorSdkUsedTest_CoreCLR.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| TestLifetime Information: Starting test Publish_UsesRazorSDK
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET DOTNET_CLI_TELEMETRY_OPTOUT=1
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET SolutionConfiguration=Release
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing command dotnet publish  --output "C:\b\t\buildTmp\5e5bdcf0-1503-4ea1-bc35-17053b095d79" --framework netcoreapp2.1 --configuration Release --no-restore 
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.6.54.9755 for .NET Core
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   ApplicationWithRazorSdkUsed -> C:\b\w\33bdfc1cae7b2a38\modules\MvcPrecompilation\testapps\ApplicationWithRazorSdkUsed\bin\Release\netcoreapp2.1\ApplicationWithRazorSdkUsed.dll
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   ApplicationWithRazorSdkUsed -> C:\b\t\buildTmp\5e5bdcf0-1503-4ea1-bc35-17053b095d79\
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet publish finished with exit code : 0
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet C:\b\t\buildTmp\5e5bdcf0-1503-4ea1-bc35-17053b095d79\ApplicationWithRazorSdkUsed.dll --server.urls http://localhost:63259/  --server Microsoft.AspNetCore.Server.Kestrel
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET DOTNET_CLI_TELEMETRY_OPTOUT=1
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET SolutionConfiguration=Release
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 2696
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Hosting environment: Production
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Content root path: C:\b\t\buildTmp\5e5bdcf0-1503-4ea1-bc35-17053b095d79
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Now listening on: http://localhost:63259
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application started. Press Ctrl+C to shut down.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Application ready at URL: http://localhost:63259/
| ApplicationWithRazorSdkUsed Warning: Retry count 1..
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request starting HTTP/1.1 GET http://localhost:63259/  
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Executing action method ApplicationWithRazorSdkUsed.Controllers.HomeController.Index (ApplicationWithRazorSdkUsed) with arguments ((null)) - ModelState is Valid
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[1]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Executing ViewResult, running view at path /Views/Home/Index.cshtml.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Executed action ApplicationWithRazorSdkUsed.Controllers.HomeController.Index (ApplicationWithRazorSdkUsed) in 6545.1073ms
| TestLifetime Information: Finished test Publish_UsesRazorSDK in 46.170132s
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request finished in 6992.4805ms 200 text/html; charset=utf-8
======= Failed test run #2 ==========
Assert.True() Failure
Expected: True
Actual:   False
   at FunctionalTests.RazorSdkUsedTest_CoreCLR.<Publish_UsesRazorSDK>d__4.MoveNext() in C:\b\w\33bdfc1cae7b2a38\modules\MvcPrecompilation\test\FunctionalTests\CoreCLRTests\RazorSdkUsedTest_CoreCLR.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| TestLifetime Information: Starting test Publish_UsesRazorSDK
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET DOTNET_CLI_TELEMETRY_OPTOUT=1
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET SolutionConfiguration=Release
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing command dotnet publish  --output "C:\b\t\buildTmp\a4581d49-2572-4596-838b-f1e9ce668c81" --framework netcoreapp2.0 --configuration Release --no-restore 
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.6.54.9755 for .NET Core
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   ApplicationWithRazorSdkUsed -> C:\b\w\33bdfc1cae7b2a38\modules\MvcPrecompilation\testapps\ApplicationWithRazorSdkUsed\bin\Release\netcoreapp2.0\ApplicationWithRazorSdkUsed.dll
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   ApplicationWithRazorSdkUsed -> C:\b\t\buildTmp\a4581d49-2572-4596-838b-f1e9ce668c81\
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet publish finished with exit code : 0
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet C:\b\t\buildTmp\a4581d49-2572-4596-838b-f1e9ce668c81\ApplicationWithRazorSdkUsed.dll --server.urls http://localhost:63300/  --server Microsoft.AspNetCore.Server.Kestrel
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET DOTNET_CLI_TELEMETRY_OPTOUT=1
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET SolutionConfiguration=Release
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 10536
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Hosting environment: Production
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Content root path: C:\b\t\buildTmp\a4581d49-2572-4596-838b-f1e9ce668c81
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Now listening on: http://localhost:63300
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application started. Press Ctrl+C to shut down.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Application ready at URL: http://localhost:63300/
| ApplicationWithRazorSdkUsed Warning: Retry count 1..
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request starting HTTP/1.1 GET http://localhost:63300/  
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Executing action method ApplicationWithRazorSdkUsed.Controllers.HomeController.Index (ApplicationWithRazorSdkUsed) with arguments ((null)) - ModelState is Valid
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[1]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Executing ViewResult, running view at path /Views/Home/Index.cshtml.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Executed action ApplicationWithRazorSdkUsed.Controllers.HomeController.Index (ApplicationWithRazorSdkUsed) in 5998.3142ms
| TestLifetime Information: Finished test Publish_UsesRazorSDK in 55.8896508s
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request finished in 6336.1145ms 200 text/html; charset=utf-8
```

**Comment by NTaylorMullen** [comment]
@mkArtakMSFT  this should probably be re-assigned to @pranavkm or @ajaybhargavb since they have more context with the SDK side of things.

**Comment by pranavkm** [comment]
This is a test from precompilation so this is the wrong repo to file this issue. That said, I re-enabled the test recently and it's been successful since. See http://aspnetci/project.html?tab=testDetails&projectId=XPlat&testNameId=8240098287330275919&page=1. We can also remove some of the runtime verification done in the test - we don't particularly care about verifying if the app runs in that test.
