### ISSUE TITLE
Using Razor runtime view compiling in standalone application

### ISSUE THREAD

**Issue by drauch** [aspnet/Razor#2122]
We want to instantiate the Razor view engine to compile Razor views into strings (essentially we want to use Razor for e-maill templating). On our development machines everything works fine, however, on deployment machines without Visual Studio installed it fails with a TypeLoadException (cannot load Microsoft.CSharp.dll - as soon as you fix this library the next one pops up, and so forth...).

What's the solution to this problem? We've observed that web projects, when published, add an additional "refs" folder with dependencies to the published output. It looks like those are the missing references. How to add those missing dependencies to the build output of a standalone console application?

Hope you can point us out how to use the Razor view engine in a "standalone" way, thanks!

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please advice how this can handled? I believe you have also a sample somewhere to do this very thing. Thanks!

**Comment by pranavkm** [comment]
You'll need to set `<PreserveCompilationContext>true</PreserveCompilationContext>` in your project file. This should produce the `refs` directory along with additional metadata required to compile views when you publish your application. If this doesn't work, could you share more details about how your project's setup? It's likely not using Microsoft.Net.Sdk.Web which usually sets up the property for you.

If you're feeling a bit more adventurous, you could also consider using build-time compilation of Razor we added as part of 2.1.0-preview1. To make it work, you

a) Reference Mvc 2.1.0-preview1 in your project (which you're likely already doing)
b) Add these two properties to your project `<RazorCompileOnBuild>true</RazorCompileOnBuild>`, `<ResolvedRazorCompileToolset>RazorSdk</ResolvedRazorCompileToolset>`.

You should see a `MyAppName.PrecompiledViews.dll` sitting next to your app's build output. This file can be used in lieu of deploying cshtml files and performing runtime compilation.

**Comment by drauch** [comment]
@pranavkm : 

1) We have PreserveCompilationContext true, however, the build output doesn't change. Maybe we need to publish the project too, however, publishing fails for this non-Web-project. The log output is:

    01.03.2018 10:15:08
    System.AggregateException: One or more errors occurred. ---> System.Exception: Publishing failed.
    (some stack trace here)

So not really helpful. Are you sure that it should be possible to publish non-Web-projects?

In regards to build-time compilation: we want to stay on 1.1.x for now. Also, we don't want build-time compilation as we want to be able to change the mail templates easily. So that is not an option for us.

**Comment by pranavkm** [comment]
> Are you sure that it should be possible to publish non-Web-projects?

It should work for console apps and web applications. Unfortunately, it's hard to give you further guidance without knowing how your project's set up. Could you share a repro application, that would help.

**Comment by drauch** [comment]
I've implemented a repro sample console application: https://www.dropbox.com/s/plleqzwycj59ch7/RazorStandaloneRepro.zip?dl=0

Works on machines with VS/.NET SDK installed. Copying the build output to a machine without those assemblies => fails to execute.

It is not possible to publish the project using Visual Studio.

Note: I've added a CopyDeps task to the csproj, so that the deps file is correctly placed in the build output. Otherwise Razor can't find its dependencies even on a machine with VS/.NET SDK installed.

**Comment by pranavkm** [comment]
> It is not possible to publish the project using Visual Studio.

You can use `dotnet publish` which should produce the deps file along with the refs directory required to compile the view.

**Comment by drauch** [comment]
@pranavkm: we cannot use the dotnet CLI right now in our CI system, we're stuck with MSBuild for now. Any ideas how to make it work using MSBuild - or even better, from within Visual Studio?

**Comment by pranavkm** [comment]
I'm not entirely sure if there's a gesture, but `msbuild /t:Publish` should work. I was also able to publish the app if I explicitly specify a `RuntimeIdentifier` in the project file

```xml
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net47</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
</PropertyGroup>
```

Once I did this, right click -> Publish worked. Having to specify `RuntimeIdentifier` seems like an odd experience bug, I'd encourage you to create a feedback (top right corner of VS -> Send Feedback) so this could be investigated.

**Comment by drauch** [comment]
Thank you! Setting the runtime identifier lets me publish the project with MSBuild! Now we're ready to ship our Razor functionality 👍

**Comment by drauch** [comment]
Uhm, no, still problems : /

@pranavkm : Now view compilation fails due to a different problem. Although a deps file and the refs folder are present and we do not have DLL-not-found problems any more, we now run into the dreaded problem that the views don't compile:

    Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
    /MailTemplates/ConfirmEmail.cshtml(4,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
    /MailTemplates/ConfirmEmail.cshtml(5,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
    /MailTemplates/ConfirmEmail.cshtml(2,3): error CS0518: Predefined type 'System.Object' is not defined or imported
    [...]

Any ideas? We thought that this problem says that we do not have the deps/refs present, but they are!

**Comment by drauch** [comment]
Weird observation: we experience the same problem on our local dev machines as long as the refs folder is present. If we remove the refs folder locally, the application is running again.

**Comment by drauch** [comment]
We observed that publishing didn't copy _all_ our deps files to the output and therefore also didn't copy all the necessary refs to the publishing output. View compilation actually happens in a library project referenced by our console application. How to instruct "MSBuild Publish" to also consider the deps files of project references?

**Comment by pranavkm** [comment]
`PreserveCompilationContext` should include all transitive references to the application. To get the scenario right, you have `App` (which is a `net47` exe), that references `Library` which is a `netstandard` class library and you notice the app's refs directory on publish does not include transitive references, is that right?

**Comment by drauch** [comment]
It's a little bit different:

`Library` is a class library project, using the new csproj format, but targetting net47 full framework. It contains the Razor view engine code and the Razor templates.

`App` is a console app project, also using the new csproj format, also targetting net47 full framework, PreserveCompilationContext and now RuntimeIdentifier is set, publishing this project creates only a single deps file (for the App) and includes only those deps in the refs folder.

**Comment by chrischu** [comment]
Is there any new information regarding this issue?

**Comment by chrischu** [comment]
I adjusted the reproduction sample provided by my colleague with our current situation and problem: 
[RazorStandaloneRepro.zip](https://github.com/aspnet/Razor/files/1796549/RazorStandaloneRepro.zip)

The application runs fine when run directly, but when it is published and the *.exe file from the publish output is run we get the following error:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
lyet1vxc.gg4(4,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(5,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(6,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(7,11): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(8,11): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(9,11): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(10,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(12,39): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(12,80): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
lyet1vxc.gg4(12,80): error CS0518: Predefined type 'System.Boolean' is not defined or imported
lyet1vxc.gg4(20,16): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(20,16): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(20,110): error CS0518: Predefined type 'System.Void' is not defined or imported
lyet1vxc.gg4(22,16): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(22,16): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(22,63): error CS0518: Predefined type 'System.Void' is not defined or imported
lyet1vxc.gg4(24,16): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(24,16): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(24,79): error CS0518: Predefined type 'System.Void' is not defined or imported
lyet1vxc.gg4(26,16): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(26,16): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(26,75): error CS0518: Predefined type 'System.Void' is not defined or imported
lyet1vxc.gg4(28,16): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(28,16): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(28,63): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(28,63): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
lyet1vxc.gg4(28,63): error CS0518: Predefined type 'System.Boolean' is not defined or imported
lyet1vxc.gg4(28,84): error CS0518: Predefined type 'System.Void' is not defined or imported
lyet1vxc.gg4(33,36): error CS1983: The return type of an async method must be void, Task or Task<T>
lyet1vxc.gg4(33,31): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(33,31): error CS0246: The type or namespace name 'Task' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(33,36): error CS0115: '_MyTemplate_cshtml.ExecuteAsync()': no suitable method found to override
lyet1vxc.gg4(15,9): error CS0518: Predefined type 'System.Void' is not defined or imported
lyet1vxc.gg4(19,10): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(19,10): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(21,10): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(21,10): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(23,10): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(23,10): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(25,10): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(25,10): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(27,10): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(27,10): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(35,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
lyet1vxc.gg4(35,29): error CS0518: Predefined type 'System.Int32' is not defined or imported
lyet1vxc.gg4(35,33): error CS0518: Predefined type 'System.Boolean' is not defined or imported
lyet1vxc.gg4(35,13): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(35,13): error CS0103: The name 'BeginContext' does not exist in the current context
lyet1vxc.gg4(36,26): error CS0518: Predefined type 'System.String' is not defined or imported
lyet1vxc.gg4(36,13): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(36,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
lyet1vxc.gg4(37,13): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(37,13): error CS0103: The name 'EndContext' does not exist in the current context
lyet1vxc.gg4(33,36): error CS0161: '_MyTemplate_cshtml.ExecuteAsync()': not all code paths return a value
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationResult.EnsureSuccessful()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromPath(String executingFilePath, String pagePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.GetView(String executingFilePath, String viewPath, Boolean isMainPage)
   at Library.RazorHtmlRenderer.<RenderAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at App.Program.Main(String[] args)

```

**Comment by chrischu** [comment]
I adapted the reproduction sample created by my colleague to our new problem (with App/Library as mentioned above by @drauch): 
[RazorStandaloneRepro.zip](https://github.com/aspnet/Razor/files/1796604/RazorStandaloneRepro.zip)

The App.exe works perfectly when run directly from the build output, however, when publishing and running the App.exe from the publish folder we get the following error:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
lyet1vxc.gg4(4,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(5,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(6,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(7,11): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(8,11): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(9,11): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(10,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(12,39): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(12,80): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
lyet1vxc.gg4(12,80): error CS0518: Predefined type 'System.Boolean' is not defined or imported
lyet1vxc.gg4(20,16): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(20,16): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(20,110): error CS0518: Predefined type 'System.Void' is not defined or imported
lyet1vxc.gg4(22,16): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(22,16): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(22,63): error CS0518: Predefined type 'System.Void' is not defined or imported
lyet1vxc.gg4(24,16): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(24,16): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(24,79): error CS0518: Predefined type 'System.Void' is not defined or imported
lyet1vxc.gg4(26,16): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(26,16): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(26,75): error CS0518: Predefined type 'System.Void' is not defined or imported
lyet1vxc.gg4(28,16): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(28,16): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(28,63): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(28,63): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
lyet1vxc.gg4(28,63): error CS0518: Predefined type 'System.Boolean' is not defined or imported
lyet1vxc.gg4(28,84): error CS0518: Predefined type 'System.Void' is not defined or imported
lyet1vxc.gg4(33,36): error CS1983: The return type of an async method must be void, Task or Task<T>
lyet1vxc.gg4(33,31): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(33,31): error CS0246: The type or namespace name 'Task' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(33,36): error CS0115: '_MyTemplate_cshtml.ExecuteAsync()': no suitable method found to override
lyet1vxc.gg4(15,9): error CS0518: Predefined type 'System.Void' is not defined or imported
lyet1vxc.gg4(19,10): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(19,10): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(21,10): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(21,10): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(23,10): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(23,10): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(25,10): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(25,10): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(27,10): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(27,10): error CS0246: The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)
lyet1vxc.gg4(35,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
lyet1vxc.gg4(35,29): error CS0518: Predefined type 'System.Int32' is not defined or imported
lyet1vxc.gg4(35,33): error CS0518: Predefined type 'System.Boolean' is not defined or imported
lyet1vxc.gg4(35,13): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(35,13): error CS0103: The name 'BeginContext' does not exist in the current context
lyet1vxc.gg4(36,26): error CS0518: Predefined type 'System.String' is not defined or imported
lyet1vxc.gg4(36,13): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(36,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
lyet1vxc.gg4(37,13): error CS0518: Predefined type 'System.Object' is not defined or imported
lyet1vxc.gg4(37,13): error CS0103: The name 'EndContext' does not exist in the current context
lyet1vxc.gg4(33,36): error CS0161: '_MyTemplate_cshtml.ExecuteAsync()': not all code paths return a value
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationResult.EnsureSuccessful()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromPath(String executingFilePath, String pagePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.GetView(String executingFilePath, String viewPath, Boolean isMainPage)
   at Library.RazorHtmlRenderer.<RenderAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at App.Program.Main(String[] args)
```

We assume that the error occurs since Razor apparently expects a `Library.deps.json` file. The problem can be circumvented
- by copying the `App.deps.json` file and renaming it to `Library.deps.json` or
- by copying the `App.deps.json` file from the build output to the publish folder.

However, both seem like pretty hacky solutions and we're not really sure if either workaround works in all cases. Is there a better way to fix the problem?

**Comment by pranavkm** [comment]
> We assume that the error occurs since Razor apparently expects a Library.deps.json file. 

Razor looks for the deps file for the hosted application given by `IHostingEnvironment.ApplicationName`. In your sample, you have it pointing to the Library which is why it's looking for the Library's deps file. Change it to point to the app and things should work:

`services.AddSingleton<IHostingEnvironment>(new HostingEnvironment { ApplicationName = "App" });`

**Comment by drauch** [comment]
Yeah, that worked :-) 👍 

Thanks for your support!
