### ISSUE TITLE
Flaky test: EnumerateItems_DiscoversAllCshtmlFiles 

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Razor#2184]
This test [failed](http://aspnetci/viewLog.html?buildId=422519&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) with the following error:
```
System.ArgumentOutOfRangeException : startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectFileSystem.<>c__DisplayClass4_0.<EnumerateItems>b__0(FileInfo file) in /_/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorProjectFileSystem.cs:line 39
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
```

Future instances of this failure will show up [here](http://aspnetci/httpAuth/app/rest/builds?locator=tag:RazorIndexRange,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, can you please handle this? Looks like a real issue.

**Comment by NTaylorMullen** [comment]
da255ff9db89ae98dbaae23d54a264bb50df2817
