### ISSUE TITLE
Flaky test: GetImportSourceDocuments_WithSuppressExceptions_UnreadableItem_DoesNotThrow

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Razor#2249]
This test [fails](http://aspnetci/viewLog.html?buildId=443262&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) occasionally with the following error:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
   at Moq.Proxy.CastleProxyFactory.CreateProxy(Type mockType, ICallInterceptor interceptor, Type[] interfaces, Object[] arguments)
   at Moq.Mock`1.<InitializeInstance>b__20_0()
   at Moq.Mock`1.OnGetObject()
   at Moq.Mock`1.get_Object()
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngineTest.GetImportSourceDocuments_WithSuppressExceptions_UnreadableItem_DoesNotThrow() in /_/test/Microsoft.AspNetCore.Razor.Language.Test/DefaultRazorProjectEngineTest.cs:line 53
```

Future instances of this failure can be seen [here](http://aspnetci/project.html?projectId=XPlat&testNameId=-2545929130564944638&tab=testDetails).

**Comment by NTaylorMullen** [comment]
Waiting for Moq to fix this.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, I think Moq is updated now. Can you please check?

**Comment by NTaylorMullen** [comment]
Given the flakiness of this test the only way I can verify that this is "fixed" is to use ILSpy or some other reflector to verify that the binaries we're currently consuming have the fix in them. Is that what you meant by check?

**Comment by mkArtakMSFT** [comment]
No, just confirm that we did update the Moq dependency and close this for now.

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg I see that in Universe we updated Moq to 4.10 nine days ago, how often do those changes flow to the underlying repos? I ask because Razor is still at 4.9

**Comment by ryanbrandenburg** [comment]
Normally the deps are updated once a week. Moq would have been brought to 4.10 [here](https://github.com/aspnet/Razor/pull/2642), but it was decided that while we moved things into a Mondo World it was more trouble than it's worth to have these dependency PR's getting created. If you find yourself in need of new deps before you're in the Mondo-repo you need only do `run.ps1 -update upgrade deps` and commit the results along with whatever it is that needs them. Alternatively you could ask Nate to bring Razor into Mondo in the next batch 😛.

**Comment by NTaylorMullen** [comment]
Ahhh, gotcha, thanks @ryanbrandenburg !
