### ISSUE TITLE
Flaky test: Lower_SetsOptions_RunsConfigureCallbacks

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Razor#2253]
This test [fails](http://aspnetci/viewLog.html?buildId=444737&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) occasionally with the following error:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
   at Moq.Proxy.CastleProxyFactory.CreateProxy(Type mockType, ICallInterceptor interceptor, Type[] interfaces, Object[] arguments)
   at Moq.Mock`1.<InitializeInstance>b__20_0()
   at Moq.Mock`1.OnGetObject()
   at Moq.Mock`1.get_Object()
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorIntermediateNodeLoweringPhaseIntegrationTest.<>c__DisplayClass1_0.<Lower_SetsOptions_RunsConfigureCallbacks>b__2(IRazorEngineBuilder b) in /_/test/Microsoft.AspNetCore.Razor.Language.Test/DefaultRazorIntermediateNodeLoweringPhaseIntegrationTest.cs:line 54
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorIntermediateNodeLoweringPhaseIntegrationTest.<>c__DisplayClass14_0.<Lower>b__0(IRazorEngineBuilder b) in /_/test/Microsoft.AspNetCore.Razor.Language.Test/DefaultRazorIntermediateNodeLoweringPhaseIntegrationTest.cs:line 443
   at Microsoft.AspNetCore.Razor.Language.RazorEngine.CreateCore(RazorConfiguration configuration, Boolean designTime, Action`1 configure) in /_/src/Microsoft.AspNetCore.Razor.Language/RazorEngine.cs:line 49
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorIntermediateNodeLoweringPhaseIntegrationTest.Lower(RazorCodeDocument codeDocument, Action`1 builder, IEnumerable`1 tagHelpers, Boolean designTime) in /_/test/Microsoft.AspNetCore.Razor.Language.Test/DefaultRazorIntermediateNodeLoweringPhaseIntegrationTest.cs:line 450
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorIntermediateNodeLoweringPhaseIntegrationTest.Lower_SetsOptions_RunsConfigureCallbacks() in /_/test/Microsoft.AspNetCore.Razor.Language.Test/DefaultRazorIntermediateNodeLoweringPhaseIntegrationTest.cs:line 50
```
Future instances of this failure can be found [here](http://aspnetci/project.html?projectId=XPlat&testNameId=4111971084968319933&tab=testDetails).

**Comment by rynowak** [comment]
If Moq is having issues this is going to affect all of our tests everywhere in the universe.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, can you please investigate this after you'll finish with your `rc1` stuff? Thanks!
