### ISSUE TITLE
Microsoft.AspNetCore.Razor.Tools.ServerCommandTest.WritePidFile_WorksAsExpected test failure

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#2303]
The build: https://ci3.dot.net/job/aspnet_Razor/job/dev/job/windows-Configuration_Release_prtest/67/
```
13:34:49   [xUnit.net 00:00:01.5014114]     Microsoft.AspNetCore.Razor.Tools.ServerCommandTest.WritePidFile_WorksAsExpected [FAIL]
13:34:49   Failed   Microsoft.AspNetCore.Razor.Tools.ServerCommandTest.WritePidFile_WorksAsExpected
13:34:50 RUNDOTNET : error Message:  [C:\Users\dotnet-bot\.dotnet\buildtools\korebuild\2.2.0-preview1-17037\KoreBuild.proj]
13:34:50    System.IO.IOException : The process cannot access the file 'C:\Users\dotnet-bot\.dotnet\pids\build\rzc-3168' because it is being used by another process.
13:34:50   Stack Trace:
13:34:50      at System.IO.FileSystem.DeleteFile(String fullPath)
13:34:50      at System.IO.File.Delete(String path)
13:34:50      at Microsoft.AspNetCore.Razor.Tools.ServerCommandTest.WritePidFile_WorksAsExpected() in /_/test/Microsoft.AspNetCore.Razor.Tools.Test/ServerCommandTest.cs:line 55
13:34:50   Invalid argument(s).
```

**Comment by pranavkm** [comment]
cc @ajaybhargavb

**Comment by ajaybhargavb** [comment]
It shouldn't fail. It doesn't fail locally or on our CI machines. Looks like it only fails on our dotnetbot Windows x64. @pranavkm, is there something special about them? Could it be something like Windows defender messing with the pid file?

**Comment by mkArtakMSFT** [comment]
As this is a test failure, I assume we can get it fixed during 2.1 timeline..

**Comment by ajaybhargavb** [comment]
Looks like this sometimes fails on our CI machines as well. https://github.com/aspnet/Razor/issues/2310#issue-318227936.

**Comment by ajaybhargavb** [comment]
7cba5ed59309b832aafe47f338399e3676b1afda
