### ISSUE TITLE
Flaky test: WritePidFile_WorksAsExpected 

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Razor#2310]
This test [fails occasionally](http://aspnetci/viewLog.html?buildId=456254&buildTypeId=Lite_Razor) with the following error:

```
System.IO.IOException : The process cannot access the file 'C:\Users\asplab\.dotnet\pids\build\rzc-3176' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Microsoft.AspNetCore.Razor.Tools.ServerCommandTest.WritePidFile_WorksAsExpected() in /_/test/Microsoft.AspNetCore.Razor.Tools.Test/ServerCommandTest.cs:line 55
```

**Comment by ajaybhargavb** [comment]
Dup of https://github.com/aspnet/Razor/issues/2303.
