### ISSUE TITLE
Flaky test: BuildIncremental_SimpleMvc_PersistsTargetInputFile

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Razor#2503]
This test [fails](http://aspnetci/viewLog.html?buildId=514689&buildTypeId=Releases_21Public_OsxUniverse) occasionally with the following error:
```
Assert.Equal() Failure
Expected: FileThumbPrint { Hash = "7jDrtMrusoaX92QPguyJZ8rpKfk=", LastWriteTimeUtc = 2018-07-25T12:16:01.0000000Z }
Actual:   FileThumbPrint { Hash = "7jDrtMrusoaX92QPguyJZ8rpKfk=", LastWriteTimeUtc = 2018-07-25T12:16:10.0000000Z }
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.BuildIncrementalismTest.<BuildIncremental_SimpleMvc_PersistsTargetInputFile>d__1.MoveNext() in /_/test/Microsoft.AspNetCore.Razor.Design.Test/IntegrationTests/BuildIncrementalismTest.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by ryanbrandenburg** [comment]
BuildIncremental_SimpleMvc_PersistsTargetInputFile [failed again](http://aspnetci/viewLog.html?buildId=515209&buildTypeId=Releases_21Public_OsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
BuildIncremental_SimpleMvc_PersistsTargetInputFile [failed again](http://aspnetci/viewLog.html?buildId=516868&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
BuildIncremental_SimpleMvc_PersistsTargetInputFile [failed again](http://aspnetci/viewLog.html?buildId=516976&buildTypeId=Releases_22xPublic_OsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please look into this? Thanks!
