### ISSUE TITLE
Flaky tests: Queue_ProcessesNotifications_AndRestarts and Queue_ProcessesNotifications_AndGoesBackToSleep

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Razor#2506]
These tests have been failing on the release/2.2 branch.

https://ci3.dot.net/job/aspnet_Razor/job/release_2.2/job/windows-Configuration_Release_prtest/29
```
Queue_ProcessesNotifications_AndRestarts [FAIL]
13:35:56    Worker should have taken all notifications
13:35:56   Expected: False
13:35:56   Actual:   True
13:35:56   Stack Trace:
13:35:56      at Microsoft.CodeAnalysis.Razor.ProjectSystem.BackgroundDocumentGeneratorTest.<Queue_ProcessesNotifications_AndRestarts>d__20.MoveNext()
13:35:56   --- End of stack trace from previous location where exception was thrown ---
13:35:56      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:35:56      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
13:35:56   --- End of stack trace from previous location where exception was thrown ---
13:35:56      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:35:56      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
13:35:56   --- End of stack trace from previous location where exception was thrown ---
13:35:56      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:35:56      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

https://dotnet.visualstudio.com/public/_build/results?buildId=8226&view=ms.vss-test-web.test-result-details

```
[FAIL] Queue_ProcessesNotifications_AndGoesBackToSleep
Queue should not have restarted
Expected: False
Actual: True

   at Microsoft.CodeAnalysis.Razor.ProjectSystem.BackgroundDocumentGeneratorTest.<Queue_ProcessesNotifications_AndGoesBackToSleep>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by NTaylorMullen** [comment]
38e145389e0e08cd0dcfb9d7b700a690fde6ea01
