### ISSUE TITLE
Competitive TagHelpers having attributes with equal names but incompatible types cause CompilationFailedException

### ISSUE THREAD

**Issue by IlyaKhD** [aspnet/Razor#570]
Sample: https://github.com/IlyaKhD/Competitive_TagHelpers_Issue

    error   : [Microsoft.AspNet.Server.WebListener.MessagePump] ProcessRequestAsync Microsoft.AspNet.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
    weiftboz.w0u(55,61): DNX,Version=v4.5.1 error CS0029: Cannot implicitly convert type 'string' to 'int'
      at Microsoft.AspNet.Mvc.Razor.Compilation.CompilationResult.EnsureSuccessful()
      at Microsoft.AspNet.Mvc.Razor.Compilation.CompilerCache.CreateCacheEntry(String normalizedPath, Func`2 compile)
      at Microsoft.AspNet.Mvc.Razor.Compilation.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
      at Microsoft.AspNet.Mvc.Razor.VirtualPathRazorPageFactory.CreateInstance(String relativePath)
      at Microsoft.AspNet.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext context, String pageName, Boolean isPartial)
      at Microsoft.AspNet.Mvc.Razor.RazorViewEngine.GetRazorPageResult(ActionContext context, String pageName, Boolean isPartial)
      at Microsoft.AspNet.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName)
      at Microsoft.AspNet.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean partial)
      at Microsoft.AspNet.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName)
      at Microsoft.AspNet.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
      at Microsoft.AspNet.Mvc.ViewResult.<ExecuteResultAsync>d__24.MoveNext()

Instead of failing with a compilation error, it would be nice to be able to select the only appropriate TagHelper in the `Process` method.

__Note__: the issue is related to https://github.com/aspnet/Razor/issues/474#issuecomment-144100186.

**Comment by NTaylorMullen** [comment]
This is by-design. In the past we talked about detecting this case at parse-time and logging a more verbose error but came to the conclusion that the C# compilation error was verbose enough to diagnose the problem.

As for selecting which `TagHelper` applies in a `Process` method, that would not be possible. At the point that the `Process` method is invoked Razor has already generated the code that tries to set a `string` to an `int`.

To work around this issue I'd recommend either of the following:
- Change attribute names to be different to avoid conflict.
- Change `[HtmlTargetElement]` to be more explicit to limit when a `TagHelper` applies.
