### ISSUE TITLE
Could not bind to System.Resources.ResourceManager in desktop .NET

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Razor#716]
When building an ASP.NET application from csproj (using packages.config, not project.json), Razor throws the following error at runtime:

> System.IO.FileNotFoundException: Could not load file or assembly 'System.Resources.ResourceManager, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Using Razor 1.0.0-rc2-20209

Repro project: [RazorError.zip](https://github.com/aspnet/Razor/files/180177/RazorError.zip)

Debug log
```
=== Pre-bind state information ===
LOG: DisplayName = System.Resources.ResourceManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Users/namc/Source/Repos/RazorError/bin/x64/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.CodeAnalysis.CSharp, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\namc\Source\Repos\RazorError\bin\x64\Debug\RazorError.vshost.exe.config
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 4.0.0.0 redirected to 4.0.1.0.
LOG: Post-policy reference: System.Resources.ResourceManager, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/Users/namc/Source/Repos/RazorError/bin/x64/Debug/System.Resources.ResourceManager.DLL.
LOG: Attempting download of new URL file:///C:/Users/namc/Source/Repos/RazorError/bin/x64/Debug/System.Resources.ResourceManager/System.Resources.ResourceManager.DLL.
LOG: Attempting download of new URL file:///C:/Users/namc/Source/Repos/RazorError/bin/x64/Debug/System.Resources.ResourceManager.EXE.
LOG: Attempting download of new URL file:///C:/Users/namc/Source/Repos/RazorError/bin/x64/Debug/System.Resources.ResourceManager/System.Resources.ResourceManager.EXE.

   at Microsoft.CodeAnalysis.CSharp.ErrorFacts.GetMessage(ErrorCode code, CultureInfo culture)
   at Microsoft.CodeAnalysis.DiagnosticInfo.GetMessage(IFormatProvider formatProvider)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.GetDiagnosticMessage(Diagnostic diagnostic)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException.FormatMessage(IEnumerable`1 compilationFailures)
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException..ctor(IEnumerable`1 compilationFailures)
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationResult.EnsureSuccessful()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String normalizedPath, Func`2 compile)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
```

**Comment by Eilon** [comment]
@NTaylorMullen can you take a look? Does it repro with the latest packages? I wonder if this was an issue with older CoreFX packages?

**Comment by ryanbrandenburg** [comment]
We tried for a while and were unable to repro this because VS is looking for "preserveCompilationContext" for the view, which it doesn't have because it's csproj not project.json.

Even before getting that far we had to do a bunch of weird nasty hacks (copying libuv.dll around, manually adding packages which were expected to load from the GAC from the \packages\ dir etc.). Do we have any way to deal with csproj projects like this with new VS tooling?

**Comment by ryanbrandenburg** [comment]
Hey @natemcmaster @NTaylorMullen and I were unable to figure this one out using your repro projects. Could you reproduce this using newer packages? The old packages of your repro projects were making it a hard to deal with.

**Comment by natemcmaster** [comment]
@ryanbrandenburg unless this is something you want to fix for RC2, I'll try to get a repro after the last-minute RC2 scurry is done. Sorry for the delay.

**Comment by natemcmaster** [comment]
Closing as so much of the CoreFX world has changed lately. I can't reproduce anymore either.
