### ISSUE TITLE
How do I address the Razor Shim CreateTrackingSpan error that Visual Studio keeps logging?

### ISSUE THREAD

**Issue by jrood** [aspnet/Razor#789]
My visual studio (2015, update 3 rc) at times becomes really unresponsive. Scrolling gets choppy, intelilisense seems to stop working, and then I can't save files. (edit: I think this is actually a seperate issue related to McAfee)

I can see many entries in my ActivityLog that all look like this
`<entry>
<record>651</record>
<time>2016/06/15 16:08:53.699</time>
<type>Error</type>
<source>Editor or Editor Extension</source>
<description>System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.&#x000D;&#x000A;Parameter name: span&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Implementation.TrackingSpan..ctor(ITextVersion version, Span span, SpanTrackingMode trackingMode)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Implementation .TextVersion.CreateTrackingSpan(Span span, SpanTrackingMode trackingMode, TrackingFidelityMode trackingFidelity)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Implementation .BaseSnapshot.CreateTrackingSpan(Span span, SpanTrackingMode trackingMode)&#x000D;&#x000A;   at Microsoft.VisualStudio.Web.Razor.Implementation .Shims.RazorSpanClassifier.OnSpansChanged(Object sender, SpansChangedEventArgs eventArgs)&#x000D;&#x000A;   at Microsoft.VisualStudio.Web.Razor .Implementation.Shims.RazorCodeGenerator.add_SpansChanged(EventHandler 1 value)&#x000D;&#x000A;   at Microsoft.VisualStudio.Web.Razor.Implementation.Shims.RazorSpanClassifier.EnsureInitialized()&#x000D;&#x000A;   at Microsoft.VisualStudio.Web.Razor.Implementation.Shims.RazorSpanClassifier .Microsoft.VisualStudio.Text.Classification.IClassifier.GetClassificationSpans(SnapshotSpan toClassifySpan)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation .ClassifierTagger.&lt;GetTags&gt;d__5.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator 1.&lt;GetTagsForBuffer&gt;d__38.MoveNext()</description>`

so there seems to be some kind of Razor.Implementation.Shims related error at CreateTrackingSpan > OnSpansChanged > add_SpansChanged > EnsureInitialized > GetClassificationSpans

**Comment by pranavkm** [comment]
Pretty stack trace:
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: span
   at Microsoft.VisualStudio.Text.Implementation.TrackingSpan..ctor(ITextVersion version, Span span, SpanTrackingMode trackingMode)
   at Microsoft.VisualStudio.Text.Implementation .TextVersion.CreateTrackingSpan(Span span, SpanTrackingMode trackingMode, TrackingFidelityMode trackingFidelity)
   at Microsoft.VisualStudio.Text.Implementation .BaseSnapshot.CreateTrackingSpan(Span span, SpanTrackingMode trackingMode)
   at Microsoft.VisualStudio.Web.Razor.Implementation .Shims.RazorSpanClassifier.OnSpansChanged(Object sender, SpansChangedEventArgs eventArgs)
   at Microsoft.VisualStudio.Web.Razor .Implementation.Shims.RazorCodeGenerator.add_SpansChanged(EventHandler 1 value)
   at Microsoft.VisualStudio.Web.Razor.Implementation.Shims.RazorSpanClassifier.EnsureInitialized()
   at Microsoft.VisualStudio.Web.Razor.Implementation.Shims.RazorSpanClassifier .Microsoft.VisualStudio.Text.Classification.IClassifier.GetClassificationSpans(SnapshotSpan toClassifySpan)
   at Microsoft.VisualStudio.Text.Classification.Implementation .ClassifierTagger.<GetTags>d__5.MoveNext()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator 1.<GetTagsForBuffer>d__38.MoveNext()
```


cc @ToddGrun

**Comment by Eilon** [comment]
Is this a VS tooling bug most likely? Should we move to the Tooling repo?

**Comment by ToddGrun** [comment]
Yes, definitely on the tooling side. Would love to have a repro project or a crash dump to investigate as we haven't seen this one before.

**Comment by jrood** [comment]
I create an issue there https://github.com/aspnet/Tooling/issues/590
I think the buggy performance actually is a different issue related to McAfee
