### ISSUE TITLE
Using razor without a webserver

### ISSUE THREAD

**Issue by nojaf** [aspnet/Razor#793]
I'm wondering if it is possible to use razor without Kestrel. 
I'd like to create a small commandline tool that fetches customer data from a database, and renders a cshtml template to create an invoice. I would render a pdf from the generated html.

I think I'm looking for something like:
```csharp
var model = GetDataFromDatabase(customerId);
string html = Razor.Render("path-to-cshtml", model);
CreatePdf(html);
```

**Comment by pranavkm** [comment]
Have a look at https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString and https://github.com/aspnet/Diagnostics/tree/dev/src/PageGenerator.

**Comment by nojaf** [comment]
Nice, thanks this will suffice.

**Comment by toddams** [comment]
But why should I provide so many services to be able to just use razor template engine? 
I mean, why should I register IHostingEnvironment and stuff like that?

**Comment by toddams** [comment]
Also when I try to launch the sample  - I get an error:

![](https://i.gyazo.com/96d443a0c94ef13c73a235a8d3ac5759.png)

**Comment by pranavkm** [comment]
@toddams - https://github.com/aspnet/Diagnostics/blob/dev/src/PageGenerator/Program.cs is pretty standalone and doesn't require any services. The other one is a wrapper over Mvc's view engine and consequently requires enough things to bootstrap. In your case, it looks like `IHostingEnvironment.ApplicationName` isn't set up correctly.

**Comment by toddams** [comment]
@pranavkm Thanks you for your feedback, bug PageGenerator sample is still a a bit confusing.
If generates a *.cs file with the following content (cut for simplicity)


```
 #pragma warning disable 1998
 public override async Task ExecuteAsync()
 {
#line 1 "Test.cshtml"
Write(model);

#line default
default
```

Is it possible to extract a ready string output?

**Comment by nojaf** [comment]
I actually have the same issue when running

```csharp
namespace ConsoleApplication
{
    public class Program
    {
        public static void Main()
        {
            // Initialize the necessary services
            var services = new ServiceCollection();
            ConfigureDefaultServices(services, customApplicationBasePath: null);

            var provider = services.BuildServiceProvider();
            var helper = provider.GetRequiredService<RazorViewToStringRenderer>();

            var model = new Person {
                FirstName = "Florian",
                LastName = "Verdonck"
            };
            var emailContent = helper.RenderViewToString("Template", model);
            Console.WriteLine(emailContent);
            Console.ReadLine();
        }

        private static void ConfigureDefaultServices(IServiceCollection services, string customApplicationBasePath)
        {
            var applicationEnvironment = PlatformServices.Default.Application;
            services.AddSingleton(applicationEnvironment);
            services.AddSingleton<IHostingEnvironment>(new HostingEnvironment
            {
                WebRootFileProvider = new PhysicalFileProvider(customApplicationBasePath ?? applicationEnvironment.ApplicationBasePath)
            });
            services.Configure<RazorViewEngineOptions>(options =>
            {
                options.FileProviders.Clear();
                options.FileProviders.Add(new PhysicalFileProvider(customApplicationBasePath ?? applicationEnvironment.ApplicationBasePath));
            });
            var diagnosticSource = new DiagnosticListener("Microsoft.AspNetCore");
            services.AddSingleton<DiagnosticSource>(diagnosticSource);
            services.AddLogging();
            Console.WriteLine("foo");
            services.AddMvc();
            services.AddSingleton<RazorViewToStringRenderer>();
        }
    }
}
```

![image](https://cloud.githubusercontent.com/assets/2621499/16478637/1f8a8398-3e9b-11e6-9f24-4bf58b9a5343.png)

How do I proceed with the IHostingEnvironment thing?

**Comment by pranavkm** [comment]
Try setting the `ApplicationName` property on the `HostingEnvironment` that you instantiate:

```
var basePath = customApplicationBasePath ?? applicationEnvironment.ApplicationBasePath;
new HostingEnvironment
{
   WebRootFileProvider = new PhysicalFileProvider(basePath),
   ApplicationName = Path.GetFileName(basePath),
});
```

**Comment by nojaf** [comment]
Still no luck

![image](https://cloud.githubusercontent.com/assets/2621499/16514029/907ac0d0-3f69-11e6-9a6c-5d98329e5015.png)

Uploaded my code to a repo, https://github.com/nojaf/RazorToHtml
Maybe I'm missing something else.

**Comment by pranavkm** [comment]
Looks like your basePath has `netcoreapp1.0` rather than the application name. Maybe just specify the project name instead: `ApplicationName = "RazorToHtml"`

**Comment by nojaf** [comment]
Ok, new error comes up.

```
$ dotnet run

Unhandled Exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.ObjectPool.ObjectPoolProvider' while attempting to activate 'Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.MvcJsonMvcOptionsSetup'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ClosedIEnumerableService.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.<>c.<AddMvcCoreServices>b__5_0(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at ConsoleApplication.Program.Main()
```

**Comment by pranavkm** [comment]
@nojaf - add this line to `ConfigureDefaultServices`:

`services.AddSingleton<ObjectPoolProvider, DefaultObjectPoolProvider>();`.

The sample in Entropy is broken with the same issue. I'll get that updated in a bit.

**Comment by pranavkm** [comment]
@nojaf see https://github.com/aspnet/Entropy/pull/147

**Comment by nojaf** [comment]
Thanks @pranavkm I got it to work.
