### ISSUE TITLE
Razor for tooling (without web)

### ISSUE THREAD

**Issue by benaadams** [aspnet/Razor#868]
Probably been raised before but can't find issue.

Use cases:

Razor for static website generation (similar to Jekyll)
Razor for "mail merge" (email generation)
etc..

**Comment by pranavkm** [comment]
* https://github.com/aspnet/Razor/tree/dev/src/RazorPageGenerator uses vanilla Razor to do templating.
* https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString uses the Mvc view engine outside of a request pipeline.

**Comment by Eilon** [comment]
@benaadams were you looking for something more than those two samples? No plans at this time for something more built-in.

**Comment by schotime** [comment]
Does the Mvc.RenderViewToString still work. I could not get it to.

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more compilation failures occurred:
Error @ (612:11,80)(30) - [The assembly 'Microsoft.AspNetCore.Mvc.Razor' could not be resolved or contains no tag helpers.] (11,80) The assembly 'Microsoft.AspNetCore.Mvc.Razor' could not be resolved or contains no tag helpers.) ---> Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
Error @ (612:11,80)(30) - [The assembly 'Microsoft.AspNetCore.Mvc.Razor' could not be resolved or contains no tag helpers.] (11,80) The assembly 'Microsoft.AspNetCore.Mvc.Razor' could not be resolved or contains no tag helpers.
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationResult.EnsureSuccessful()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Mvc.RenderViewToString.RazorViewToStringRenderer.<RenderViewToStringAsync>d__4`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Mvc.RenderViewToString.Program.Main(String[] args)
```

**Comment by rynowak** [comment]
@schotime  - Please open a new issue and describe the problem you are having fully so we can help you
